# Generated by Django 5.1 on 2025-10-10 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0072_stationmanager'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenCycleDailyMetrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cycle_time_required', models.FloatField(blank=True, null=True)),
                ('cycle_time_actual_1', models.FloatField(blank=True, null=True)),
                ('cycle_time_actual_2', models.FloatField(blank=True, null=True)),
                ('cycle_time_actual_3', models.FloatField(blank=True, null=True)),
                ('cycle_time_actual_4', models.FloatField(blank=True, null=True)),
                ('cycle_time_actual_5', models.FloatField(blank=True, null=True)),
                ('cycle_time_actual_6', models.FloatField(blank=True, null=True)),
                ('cycle_time_actual_7', models.FloatField(blank=True, null=True)),
                ('cycle_time_actual_8', models.FloatField(blank=True, null=True)),
                ('cycle_time_actual_9', models.FloatField(blank=True, null=True)),
                ('cycle_time_actual_10', models.FloatField(blank=True, null=True)),
                ('quality_rate', models.FloatField(blank=True, null=True)),
                ('productivity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='app1.tencycledayconfiguration')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='app1.operatorperformanceevaluation')),
            ],
            options={
                'unique_together': {('evaluation', 'day')},
            },
        ),
    ]
