# Generated by Django 5.1 on 2025-10-10 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0073_tencycledailymetrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineeinfo',
            name='station_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='app1.station'),
        ),
    ]
