# Generated by Django 5.1 on 2025-10-13 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0074_traineeinfo_station_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ojtlevel2quantity',
            name='station_name',
        ),
        migrations.RemoveField(
            model_name='traineeinfo',
            name='station',
        ),
        migrations.AddField(
            model_name='ojtlevel2quantity',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantity_trainees', to='app1.station'),
        ),
    ]
