# Generated by Django 5.1 on 2025-10-13 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0075_remove_ojtlevel2quantity_station_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='traineeinfo',
            old_name='station_id',
            new_name='station',
        ),
    ]
