# Generated by Django 5.1 on 2025-10-13 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0076_rename_station_id_traineeinfo_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnualPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_name', models.CharField(max_length=100)),
                ('plan_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annual_plans', to='app1.mastertable')),
            ],
            options={
                'ordering': ['-plan_date'],
                'unique_together': {('employee', 'plan_date')},
            },
        ),
        migrations.CreateModel(
            name='ObservationSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=100)),
                ('date_of_evaluation', models.DateField()),
                ('shift', models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('General', 'General')], max_length=20)),
                ('observer_name', models.CharField(max_length=100)),
                ('total_marks', models.IntegerField()),
                ('marks_obtained', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('N/A', 'N/A')], max_length=20)),
                ('root_cause_analysis', models.TextField(blank=True, null=True)),
                ('counteraction', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observation_sheet', to='app1.annualplan')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.CharField(max_length=500)),
                ('day1', models.CharField(choices=[('1', 'Yes (1)'), ('0', 'No (0)'), ('X', 'NC (X)'), ('N/A', 'Not Applicable'), ('', '-')], default='', max_length=5)),
                ('day2', models.CharField(choices=[('1', 'Yes (1)'), ('0', 'No (0)'), ('X', 'NC (X)'), ('N/A', 'Not Applicable'), ('', '-')], default='', max_length=5)),
                ('day3', models.CharField(choices=[('1', 'Yes (1)'), ('0', 'No (0)'), ('X', 'NC (X)'), ('N/A', 'Not Applicable'), ('', '-')], default='', max_length=5)),
                ('day4', models.CharField(choices=[('1', 'Yes (1)'), ('0', 'No (0)'), ('X', 'NC (X)'), ('N/A', 'Not Applicable'), ('', '-')], default='', max_length=5)),
                ('day5', models.CharField(choices=[('1', 'Yes (1)'), ('0', 'No (0)'), ('X', 'NC (X)'), ('N/A', 'Not Applicable'), ('', '-')], default='', max_length=5)),
                ('day6', models.CharField(choices=[('1', 'Yes (1)'), ('0', 'No (0)'), ('X', 'NC (X)'), ('N/A', 'Not Applicable'), ('', '-')], default='', max_length=5)),
                ('marks', models.CharField(blank=True, max_length=10)),
                ('nc_details', models.CharField(blank=True, max_length=50)),
                ('result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('N/A', 'N/A')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('observation_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_lines', to='app1.observationsheet')),
            ],
        ),
    ]
