# Generated by Django 5.1 on 2025-10-13 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0077_annualplan_observationsheet_observationlineitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenCycleSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_engineer_name', models.CharField(max_length=100)),
                ('qa_engineer_name', models.CharField(max_length=100)),
                ('operator_name', models.CharField(max_length=20)),
                ('operator_id', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('machine', models.CharField(blank=True, max_length=100)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('part_name', models.CharField(blank=True, max_length=100)),
                ('sop_no', models.CharField(blank=True, max_length=50)),
                ('checked_by', models.CharField(blank=True, max_length=50)),
                ('verified_by', models.CharField(blank=True, max_length=50)),
                ('reviewed_by', models.CharField(blank=True, max_length=50)),
                ('approved_by', models.CharField(blank=True, max_length=50)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tencycle_sheets', to='app1.department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tencycle_sheets', to='app1.mastertable')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tencycle_sheets', to='app1.level')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tencycle_sheets', to='app1.line')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tencycle_sheets', to='app1.station')),
            ],
        ),
        migrations.CreateModel(
            name='TencycleEntrySheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.CharField(max_length=20)),
                ('q1', models.BooleanField(default=True)),
                ('q2', models.BooleanField(default=True)),
                ('q3', models.BooleanField(default=True)),
                ('q4', models.BooleanField(default=True)),
                ('a_q1', models.BooleanField(default=True)),
                ('a_q2', models.BooleanField(default=True)),
                ('a_q3', models.BooleanField(default=True)),
                ('a_q4', models.BooleanField(default=True)),
                ('a_q5', models.BooleanField(default=True)),
                ('general_points_a', models.BooleanField(default=True)),
                ('cycle_1', models.FloatField(blank=True, null=True)),
                ('cycle_2', models.FloatField(blank=True, null=True)),
                ('cycle_3', models.FloatField(blank=True, null=True)),
                ('cycle_4', models.FloatField(blank=True, null=True)),
                ('cycle_5', models.FloatField(blank=True, null=True)),
                ('cycle_6', models.FloatField(blank=True, null=True)),
                ('cycle_7', models.FloatField(blank=True, null=True)),
                ('cycle_8', models.FloatField(blank=True, null=True)),
                ('cycle_9', models.FloatField(blank=True, null=True)),
                ('cycle_10', models.FloatField(blank=True, null=True)),
                ('cycle_time_spec', models.CharField(max_length=20)),
                ('avg_cycle_time', models.FloatField(blank=True, null=True)),
                ('result_marking_b', models.BooleanField(default=True)),
                ('cross_inspection_c', models.IntegerField()),
                ('skill_level', models.CharField(blank=True, max_length=50)),
                ('observation_total', models.CharField(blank=True, max_length=100)),
                ('pass_score', models.CharField(blank=True, max_length=100)),
                ('overall_result', models.CharField(blank=True, max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app1.tencyclesheet')),
            ],
        ),
    ]
