# Generated by Django 5.1 on 2025-10-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0078_tencyclesheet_tencycleentrysheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tencyclesheet',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='tencyclesheet',
            name='model_name',
        ),
        migrations.RemoveField(
            model_name='tencyclesheet',
            name='operator_id',
        ),
        migrations.RemoveField(
            model_name='tencyclesheet',
            name='operator_name',
        ),
    ]
