# Generated by Django 5.1 on 2025-10-15 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0079_remove_tencyclesheet_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tencyclesheet',
            name='annual_plan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tencycle_sheet', to='app1.annualplan'),
        ),
        migrations.AlterField(
            model_name='traineeinfo',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='app1.station'),
        ),
    ]
