# Generated by Django 5.1 on 2025-11-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0083_templatequestion_option_a_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='raw_answers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
