# Generated by Django 5.1 on 2025-11-10 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0085_biouser_biometricattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoversheet',
            name='allocated_line',
            field=models.ForeignKey(blank=True, help_text='The specific line within the department the employee was allocated to during this handover.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.line'),
        ),
        migrations.AddField(
            model_name='handoversheet',
            name='allocated_station',
            field=models.ForeignKey(blank=True, help_text='The specific station the employee was allocated to during this handover.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.station'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='current_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_on_line', to='app1.line'),
        ),
        migrations.AddField(
            model_name='mastertable',
            name='current_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees_at_station', to='app1.station'),
        ),
    ]
