# Generated by Django 5.1 on 2025-11-10 09:16

import app1.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0086_handoversheet_allocated_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='aadhar_number',
            field=models.CharField(blank=True, help_text='12-digit Aadhar number', max_length=12, null=True, validators=[app1.models.aadhar_validator]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and up to two spaces (no numbers or special characters).', regex='^[A-Za-z]+(?: [A-Za-z]+){0,2}$')]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Name must contain only letters and up to two spaces (no numbers or special characters).', regex='^[A-Za-z]+(?: [A-Za-z]+){0,2}$')]),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[app1.models.phone_number_validator]),
        ),
    ]
