# Generated by Django 5.1 on 2025-11-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0087_userregistration_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mastertable',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
