# Generated by Django 5.1 on 2025-11-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0090_alter_mastertable_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastertable',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
