# Generated by Django 5.1 on 2025-11-17 09:20

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0092_alter_templatequestion_correct_answer_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='retrainingconfig',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='traineeinfo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='operatorperformanceevaluation',
            name='attempt_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='score',
            name='attempt_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='traineeinfo',
            name='approved_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='traineeinfo',
            name='attempt_no',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='traineeinfo',
            name='created_at',
            # field=models.DateTimeField(auto_now_add=True, default=1),
            field=models.DateTimeField(auto_now_add=True, default=timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traineeinfo',
            name='prepared_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='traineeinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='operatorperformanceevaluation',
            name='final_status',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Not Evaluated', 'Not Evaluated')], default='Not Evaluated', max_length=30),
        ),
        migrations.AlterField(
            model_name='retrainingconfig',
            name='evaluation_type',
            field=models.CharField(choices=[('Evaluation', 'Evaluation'), ('OJT', 'OJT'), ('10 Cycle', '10 Cycle')], max_length=20, unique=True),
        ),
        migrations.AddIndex(
            model_name='traineeinfo',
            index=models.Index(fields=['emp_id', 'station', 'level'], name='app1_traine_emp_id_15967c_idx'),
        ),
        migrations.RemoveField(
            model_name='retrainingconfig',
            name='level',
        ),
    ]
