# Generated by Django 5.1 on 2025-11-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0093_alter_retrainingconfig_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrainingsession',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Missed', 'Missed')], default='Pending', max_length=16),
        ),
    ]
