# Generated by Django 5.1 on 2025-11-26 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0094_alter_retrainingsession_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='advancemanpowerdashboard',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='managementreview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='advancemanpowerdashboard',
            name='l1_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancemanpowerdashboard',
            name='l1_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancemanpowerdashboard',
            name='l2_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancemanpowerdashboard',
            name='l2_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancemanpowerdashboard',
            name='l3_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancemanpowerdashboard',
            name='l3_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancemanpowerdashboard',
            name='l4_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancemanpowerdashboard',
            name='l4_required',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='advancemanpowerdashboard',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.line'),
        ),
        migrations.AddField(
            model_name='advancemanpowerdashboard',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.station'),
        ),
        migrations.AddField(
            model_name='advancemanpowerdashboard',
            name='subline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.subline'),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='gca_defects',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.line'),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='manpower_available',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='manpower_required',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.station'),
        ),
        migrations.AddField(
            model_name='managementreview',
            name='subline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.subline'),
        ),
        migrations.AlterUniqueTogether(
            name='advancemanpowerdashboard',
            unique_together={('hq', 'factory', 'department', 'line', 'subline', 'station', 'month', 'year')},
        ),
    ]
