# Generated by Django 5.1 on 2025-12-10 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0097_actionitem_actionitemrejection'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelDayRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required_days', models.PositiveSmallIntegerField(help_text='Number of days needed to complete OJT')),
                ('level', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='day_requirement', to='app1.level')),
            ],
            options={
                'ordering': ['level__level_id'],
            },
        ),
    ]
