# Generated by Django 5.1 on 2025-12-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0098_leveldayrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
