# Generated by Django 5.2.7 on 2025-12-11 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0099_alter_userregistration_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiometricDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Main Gate, Lathe Shop Device', max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='e.g. 192.168.1.50', null=True)),
                ('port', models.IntegerField(default=85)),
                ('serial_number', models.CharField(blank=True, help_text='SN from Device Sticker (CLH...)', max_length=50, unique=True)),
                ('is_attendance_device', models.BooleanField(default=False, help_text='If True, syncs ALL users automatically.')),
                ('is_enrollment_device', models.BooleanField(default=False, help_text='Dojo Room Device')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='biouser',
            name='has_face',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biouser',
            name='has_fingerprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='biouser',
            name='last_status_sync',
            field=models.DateTimeField(blank=True, help_text='Last time we checked EasyTime for bio data', null=True),
        ),
        migrations.AlterField(
            model_name='biouser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='machine',
            name='biometric_device',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine_link', to='app1.biometricdevice'),
        ),
        migrations.CreateModel(
            name='BiometricEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synced_at', models.DateTimeField(auto_now_add=True)),
                ('bio_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='app1.biouser')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_users', to='app1.biometricdevice')),
            ],
            options={
                'verbose_name': 'Enrolled User Log',
                'unique_together': {('bio_user', 'device')},
            },
        ),
        migrations.CreateModel(
            name='LocalAttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_sn', models.CharField(max_length=50)),
                ('punch_time', models.DateTimeField()),
                ('area_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('log_type', models.CharField(default='MACHINE', max_length=20)),
                ('bio_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app1.biouser')),
            ],
            options={
                'ordering': ['-punch_time'],
                'unique_together': {('bio_user', 'punch_time', 'device_sn')},
            },
        ),
    ]
