# Generated by Django 5.1 on 2025-12-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0101_alter_trainingbatch_batch_id_rescheduledsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='rescheduledsession',
            name='attendance_photo',
            field=models.ImageField(blank=True, help_text='Photo taken when marking attendance for rescheduled session', null=True, upload_to='rescheduled_attendance_photos/'),
        ),
    ]
