# Generated by Django 5.2.5 on 2025-12-23 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0102_rescheduledsession_attendance_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorDailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('first_punch', models.DateTimeField()),
                ('last_punch', models.DateTimeField()),
                ('employee_name_snapshot', models.CharField(blank=True, max_length=100)),
                ('device_name_snapshot', models.CharField(blank=True, max_length=100)),
                ('bio_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.biouser')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.biometricdevice')),
            ],
            options={
                'ordering': ['-date', 'bio_user'],
                'unique_together': {('bio_user', 'device', 'date')},
            },
        ),
    ]
