# Generated by Django 5.2.5 on 2026-07-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0103_operatordailylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineallocation',
            name='access_date',
            field=models.DateField(blank=True, help_text='The date this temporary access expires.', null=True),
        ),
        migrations.AddField(
            model_name='machineallocation',
            name='biometric_status',
            field=models.CharField(choices=[('not_synced', 'Not Synced'), ('active', 'Active – Unblocked on Device'), ('blocked', 'Blocked on Device')], default='not_synced', help_text='Tracks whether the employee is active or blocked on the biometric device.', max_length=20),
        ),
        migrations.AddField(
            model_name='machineallocation',
            name='is_temporary',
            field=models.BooleanField(default=False, help_text='If True, this is emergency/temporary access valid until access_date.'),
        ),
    ]
